// packages/code-angular/src/components/badge.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import type { BadgeVariant } from '@uwckit/code-core';
import '@uwckit/code-core';

@Component({
  selector: 'uwckit-badge',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <uwc-badge
      [attr.variant]="variant"
      [attr.dot]="dot || null"
    >
      <ng-content></ng-content>
    </uwc-badge>
  `,
})
export class UwckitBadgeComponent {
  @Input() variant: BadgeVariant = 'default';
  @Input() dot = false;
}

// packages/code-react/src/components/Badge.tsx
import React from 'react';
import type { BadgeVariant } from '@uwckit/code-core';
import '@uwckit/code-core';

export interface BadgeProps {
  variant?: BadgeVariant;
  dot?: boolean;
  children?: React.ReactNode;
}

export const Badge: React.FC<BadgeProps> = ({
  variant = 'default',
  dot = false,
  children,
}) => (
  <uwc-badge variant={variant} dot={dot || undefined}>
    {children}
  </uwc-badge>
);
