// packages/code-angular/src/components/button.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import type { ButtonVariant, ButtonSize } from '@uwckit/code-core';
import '@uwckit/code-core';

@Component({
  selector: 'uwckit-button',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <uwc-button
      [attr.variant]="variant"
      [attr.size]="size"
      [attr.disabled]="disabled || null"
      [attr.loading]="loading || null"
      [attr.type]="type"
      (uwc-click)="clicked.emit($event)"
    >
      <ng-content></ng-content>
    </uwc-button>
  `,
})
export class UwckitButtonComponent {
  @Input() variant: ButtonVariant = 'primary';
  @Input() size: ButtonSize = 'md';
  @Input() disabled = false;
  @Input() loading = false;
  @Input() type: 'button' | 'submit' | 'reset' = 'button';

  @Output() clicked = new EventEmitter<Event>();
}

// packages/code-react/src/components/Button.tsx
import React, { useCallback } from 'react';
import type { ButtonVariant, ButtonSize } from '@uwckit/code-core';
import '@uwckit/code-core';

export interface ButtonProps {
  variant?: ButtonVariant;
  size?: ButtonSize;
  disabled?: boolean;
  loading?: boolean;
  type?: 'button' | 'submit' | 'reset';
  children?: React.ReactNode;
  onClick?: (event: Event) => void;
  className?: string;
}

export const Button: React.FC<ButtonProps> = ({
  variant = 'primary',
  size = 'md',
  disabled = false,
  loading = false,
  type = 'button',
  children,
  onClick,
  className,
}) => {
  const ref = useCallback(
    (node: HTMLElement | null) => {
      if (!node) return;
      const handler = (e: Event) => onClick?.(e);
      node.addEventListener('uwc-click', handler);
      return () => node.removeEventListener('uwc-click', handler);
    },
    [onClick]
  );

  return (
    <uwc-button
      ref={ref as any}
      variant={variant}
      size={size}
      disabled={disabled || undefined}
      loading={loading || undefined}
      type={type}
      className={className}
    >
      {children}
    </uwc-button>
  );
};
