// packages/code-angular/src/components/card.component.ts
import {
  Component,
  Input,
  ChangeDetectionStrategy,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import '@uwckit/code-core';

@Component({
  selector: 'uwckit-card',
  standalone: true,
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <uwc-card [attr.hoverable]="hoverable || null">
      <ng-content select="[slot=header]"></ng-content>
      <ng-content></ng-content>
      <ng-content select="[slot=footer]"></ng-content>
    </uwc-card>
  `,
})
export class UwckitCardComponent {
  @Input() hoverable = false;
}

// packages/code-react/src/components/Card.tsx
import React from 'react';
import '@uwckit/code-core';

export interface CardProps {
  hoverable?: boolean;
  header?: React.ReactNode;
  footer?: React.ReactNode;
  children?: React.ReactNode;
}

export const Card: React.FC<CardProps> = ({
  hoverable = false,
  header,
  footer,
  children,
}) => (
  <uwc-card hoverable={hoverable || undefined}>
    {header && <span slot="header">{header}</span>}
    {children}
    {footer && <span slot="footer">{footer}</span>}
  </uwc-card>
);
